name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Prerequisites
        if: runner.os == 'macOs'
        run: brew install gawk
      - name: Build
        run: make
      - name: Test
        run: make check
